/**
 * prisma.config.ts — Prisma CLI 配置文件
 *
 * 作用：告诉 Prisma CLI（`npx prisma migrate/generate` 等命令）
 *   - schema 文件位置
 *   - 迁移脚本目录
 *   - 使用的底层引擎（classic = Rust 引擎）
 *   - 数据库连接串来源（从 .env 读取 DATABASE_URL）
 *
 * 何时生效：执行任何 prisma CLI 命令时自动加载。
 * 不是运行时脚本，不直接产生数据。
 */
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
